### ISSUE TITLE
Error: could not connect after timeout at eval (Room.js?b64e:86)

### ISSUE THREAD

**Issue by zhuwei** [livekit/client-sdk-js#19] opened 2021-07-27 09:47 UTC
![image](https://user-images.githubusercontent.com/1817493/127133491-50cb1d58-acb6-4770-8c34-cbb78baaf559.png)

你好，我调用connect后，大约await 5秒，就会抛出异常，无法继续。

**Comment by davidzhao** [comment] 2021-07-27 19:48
This is a duplicate of #9 . let's continue the discussion there.

**Closed by davidzhao** 2021-07-27 19:48 UTC
