### ISSUE TITLE
iOS: Can't see remote participant camera feed (chrome) #1094

### ISSUE THREAD

**Issue by AurimasG12** [livekit/client-sdk-js#1095] opened 2024-03-29 05:57 UTC
### Describe the bug

I should see remote participant camera feed, but at the moment - remote participant camera feed is muted.

### Reproduction

- Open https://meet.livekit.io/ with computer
- Create room with enabled end to end encryption
- Join room
- Pick up iphone <= 13 or simulator (browserstack) and choose iOS version 15 and open chrome
- Try to join same room as in computer (copy link first from after second step, do not forget to include password)
- Accept permissions

I used real Iphone 8 with iOs 16.7. Also reproduced this case with Iphone iOs 15 simulator in browserstack.

### System Info

```shell
Iphone 8 with iOs 16.7.
Iphone 13 simulator with iOs 15

Browser: chrome
```

### Severity

blocking all usage of LiveKit

**Comment by davidzhao** [comment] 2024-04-01 05:32
To be clear, you are only able to reproduce the issue with:
* iPhone 13
* iOS 15
* E2EE enabled
* Using Chrome on iPhone
?

I've tested with iOS 17 on iPhone 15 and it works as expected. It'll be helpful if you can confirm the first version that does work for you.

**Comment by AurimasG12** [comment] 2024-04-02 07:53
> To be clear, you are only able to reproduce the issue with:
> 
> * iPhone 13
> * iOS 15
> * E2EE enabled
> * Using Chrome on iPhone
>   ?
> 
> I've tested with iOS 17 on iPhone 15 and it works as expected. It'll be helpful if you can confirm the first version that does work for you.

iphone 13 with iOS 17 works fine. Looks like iOS < 17 does not work

**Comment by arnasledev** [comment] 2024-04-02 08:32
Reproducing also. Using https://meet.livekit.io 

![image](https://github.com/livekit/client-sdk-js/assets/39725714/c5a20eb0-f491-4450-9e78-ef6eb1abe0ef)
![image](https://github.com/livekit/client-sdk-js/assets/39725714/1c9d7549-9778-4957-aa05-62b526dba02f)

**Comment by lukasIO** [comment] 2024-04-05 11:58
did some tests with browserstack:
- Chrome, iOS 16: works
- Chrome, iOS 17: works
- Chrome, iOS 15: websocket connection doesn't establish/fails with error code 1006

As it seems you're able to get the websocket connection to work with iOS 15 (not sure why this is failing for me on browserstack), could you pull and post the client logs you get on both the iOS and desktop device?

**Comment by davidzhao** [comment] 2024-04-06 18:03
End to end encryption uses [RTCRtpScriptTransform](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpScriptTransform) and requires Safari 15.4+. I don't think iOS 15 ships with that version of Safari.

**Comment by AurimasG12** [comment] 2024-04-08 07:35
> did some tests with browserstack:
> 
> * Chrome, iOS 16: works
> * Chrome, iOS 17: works
> * Chrome, iOS 15: websocket connection doesn't establish/fails with error code 1006
> 
> As it seems you're able to get the websocket connection to work with iOS 15 (not sure why this is failing for me on browserstack), could you pull and post the client logs you get on both the iOS and desktop device?

I cannot reproduce anymore in meet.livekit.io with iOS 16, but can reproduce in my project.
I've checked the server logs and found publish time out error:
<img width="1313" alt="image" src="https://github.com/livekit/client-sdk-js/assets/51153447/8d5a844b-d1b7-4988-a42a-d0048b72eee8">

**Comment by davidzhao** [comment] 2024-04-23 06:20
closing since this is a known issue with iOS 15

**Closed by davidzhao** 2024-04-23 06:20 UTC
