### ISSUE TITLE
iOS: Can't see remote participant camera feed (chrome + browserstack)

### ISSUE THREAD

**Issue by AurimasG12** [livekit/client-sdk-js#1113] opened 2024-04-23 08:35 UTC
### Describe the bug

I expect to see iOS user camera feed on my pc user.

### Reproduction

Participant A:
1. Open meet.livekit.io select custom tab
2. In cloud.livekit.io generate token for pc user
3. Connect meeting with generated credentials with pc user, dont forget to enable end-to-end encryption

Participant B:
1. Open meet.livekit.io using iphone 16.x (I have used browserstack) and select custom tab
2. In cloud.livekit.io generate token for ios user
3. Connect meeting with generated credentials with ios user, dont forget to enable end-to-end encryption

Video recording: https://drive.google.com/file/d/1f9crmFMie-PCt0cx4M_1f-zZVZ5ohAo2/view?usp=sharing
Logs:
[pc_user.log](https://github.com/livekit/client-sdk-js/files/15073870/pc_user.log)
[ios_user.log](https://github.com/livekit/client-sdk-js/files/15073871/ios_user.log)

### System Info

```shell
Participant A: System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1
    Memory: 133.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.62
    Edge: 124.0.2478.51
    Safari: 17.1

Participant B: Iphone 13 iOS 16.3 Chrome
```

### Severity

blocking all usage of LiveKit

### Additional Information
Cloud server config
![image](https://github.com/livekit/client-sdk-js/assets/51153447/5edcc42b-8ade-4943-9c17-8776037bdacd)

_No response_

**Comment by lukasIO** [comment] 2024-04-23 11:02
In your settings you have vp8 disabled, vp9 and av1 are not supported for end-to-end encryption.
Does it start working if you enable vp8 as a codec?

**Comment by AurimasG12** [comment] 2024-04-24 04:59
> In your settings you have vp8 disabled, vp9 and av1 are not supported for end-to-end encryption. Does it start working if you enable vp8 as a codec?

No, it does not work.

**Comment by lukasIO** [comment] 2024-04-24 06:41
Did you ensure that you were actually publishing and receiving vp8 ?

**Comment by AurimasG12** [comment] 2024-04-24 08:35
ios user log: 
<img width="385" alt="image" src="https://github.com/livekit/client-sdk-js/assets/51153447/44771ce9-74fd-41ec-ae30-8e4bd8fe5d0e">
pc user log: 
<img width="656" alt="image" src="https://github.com/livekit/client-sdk-js/assets/51153447/435c5fed-422c-4e6b-aaf3-3fef6aa7152a">

**Comment by lukasIO** [comment] 2024-04-24 09:30
I just tested this on browserstack with iOS16 and chrome as a browser. I see the same behaviour as you.
The reason for this is probably the fact that browserstack doesn't send any updated video frames (as the video is black/static). In order for a LiveKit track to be successfully published and broadcasted to other users server side, media needs to be flowing. This does not seem to be the case here. 
I'll close this as won't fix, but feel free to re-open if you can reproduce this with an actual device and a working camera.

**Comment by lukasIO** [comment] 2024-04-24 10:22
reopening as @AurimasG12 can repro on a real device

**Closed** 2024-04-25 15:11 UTC
