### ISSUE TITLE
reconnected participants, continue seeing non-exist participants

### ISSUE THREAD

**Issue by salihsagdilek** [livekit/client-sdk-js#561] opened 2023-01-27 11:27 UTC
### Describe the bug

when someone lost the connection and while he trying to reconnect someone else leaves the room, he misses room events when reconnecting. And when reconnected he continues to see participants that left.

### Reproduction

https://www.loom.com/share/e3dc8d37adab4090837a8a4cde67c2cc

### System Info

```shell
any
```

### Severity

serious, but I can work around it

**Comment by lukasIO** [comment] 2023-01-31 10:15
hi @salihsagdilek 
thank you for the report!
I tried a similar setup with all participants on example.livekit.io, but the participant who disconnected immediately disappeared after the reconnection was successful... 

What is intended behavior: 
ParticipantConnected and ParticipantDisconnected events will _not_ be emitted during reconnections. The idea is that after a reconnection you can check/loop over the participants like you would after connecting to a room for the first time.
Does this help?

**Comment by salihsagdilek** [comment] 2023-01-31 13:50
Hello @lukasIO, we have recorded same issue on example.livekit.io.

example.livekit.io = https://www.loom.com/share/4c5a9110318245efbc58edf0b665b03a
livekit.io/playground = https://www.loom.com/share/e3dc8d37adab4090837a8a4cde67c2cc

**Comment by davidzhao** [comment] 2023-02-01 06:04
The example demo is showing that when a user's internet connection completely dies, they would remain in the room but without video data. I do not see any reconnection attempts from the video.

this is expected, there's about a 15-30s lag after a participant loses connectivity, can we be sure that they've really left. when the participant leaves normally, clients would send an event to the server indicating that they have left.

**Comment by fatihorhan** [comment] 2023-02-01 08:38
Hello @davidzhao.

I helped @salihsagdilek when preparing the video.
We have 3 participants in the room to make sure there's a bug. I want to give more details:
- You see the video from the perspective of Participant 1. He disconnects his internet and comes back within 5 seconds. He sees Participant 2 and 3 when he comes back although Participant 2 is actually left when he was away.
- Participant 2 leaves the room 1 second after Participant 1 is left
- Participant 3 is in the room the whole time (as a control group). He sees Participant 1 freeze for 5 seconds, then comeback. He also sees Participant 2 leave. So Participant 3 only sees Participant 1 at the end of experiment.

I hope this clears things up.

**Comment by salihsagdilek** [comment] 2023-02-03 13:13
It's happening in reconnecting state. you know After a certain period of time reconnecting state interval is ended, when interval clearing and participant connect manually is fixing the issue.

**Comment by lukasIO** [comment] 2023-03-10 16:29
fixed in https://github.com/livekit/client-sdk-js/pull/605

**Closed by lukasIO** 2023-03-10 16:29 UTC
