### ISSUE TITLE
Returning RemoteTrackPublication id from localParticipant.publishTrack function

### ISSUE THREAD

**Issue by gokhanatalay** [livekit/client-sdk-js#550] opened 2023-01-03 14:04 UTC
### Describe the problem

I need to deliver the remote track ids of the users connected over the socket to other broadcast users, but the localParticipant.publishTrack function does not return this value.

### Describe the proposed solution

The localParticipant.publishTrack function returns the RemoteTrackPublication id along with LocalTrackPublication.

### Alternatives considered

Publishing a video with sound with localParticipant.publishTrack function and matching video and audio.

### Importance

would make my life easier

**Comment by lukasIO** [comment] 2023-01-03 14:29
Hi, 
what value in particular is missing for you that you would like to map? 
`publication.trackSid` should be available!

**Comment by gokhanatalay** [comment] 2023-01-05 12:48
Video track is not publish.

![image](https://user-images.githubusercontent.com/15022867/210783676-338d818c-d22e-462c-96bc-29fd48982867.png)

![image](https://user-images.githubusercontent.com/15022867/210783173-52b9d28e-f886-49cf-97ac-65a1604b42f0.png)

**Comment by gokhanatalay** [comment] 2023-01-05 12:56
I'm trying to stream local video.

![carbon (1)](https://user-images.githubusercontent.com/15022867/210784933-a23eff59-db49-4452-a3e7-1fcefa5664aa.png)


`
if (!livekit_room.localParticipant.isScreenShareEnabled) {
	let name = JSON.parse(livekit_room.localParticipant.metadata).name;
	let surname = JSON.parse(livekit_room.localParticipant.metadata).surname;
	let videoTitle = `${name} ${surname.charAt(0)}.'s Video`;
​
	const inputElement = document.createElement("input");
	inputElement.type = "file";
	inputElement.accept= "video/mp4,video/x-m4v,video/*";
	inputElement.click();
	inputElement.oninput = (e) => {
		const videoElement = document.createElement("video");
		const fileURL = URL.createObjectURL(inputElement.files[0]);
		videoElement.src = fileURL;
		videoElement.crossOrigin = 'anonymous';
		videoElement.autoplay = true;
		videoElement.loop = true;
		videoElement.volume = 0;
		// videoElement.load();
		// videoElement.play();
		videoElement.addEventListener('loadedmetadata', async () => {
			let stream;
			const fps = 0;
			// @ts-ignore
			if (videoElement.captureStream) {
				// @ts-ignore
				stream = videoElement.captureStream(fps);
				// @ts-ignore
			} else if (videoElement.mozCaptureStream) {
				// @ts-ignore
				stream = videoElement.mozCaptureStream(fps);
			} else {
				console.error('Stream capture is not supported');
				stream = null;
				return;
			}
​
			let track, trackAudio;
			Promise.all([
				track = await livekit_room.localParticipant.publishTrack(stream.getVideoTracks()[0]),
				trackAudio = await livekit_room.localParticipant.publishTrack(stream.getAudioTracks()[0]),
			]).then(() => {
				addSourceFromStream(
					track.track,
					trackAudio.track, TrackType.Video,
					screenShareTitle,
					track.trackSid, videoTitle, livekit_room.localParticipant.identity,
					true, 0, videoElement)
				$authStore.muted.screen_share = false
			})
		});
	};
}
`

**Comment by lukasIO** [comment] 2023-01-05 16:16
So the problem is that your locally generated video publications do not get published?

Do you receive the `LocalTrackPublished` events on the publisher side after publishing those tracks?
I guess `fps` being 0 could potentially be a problem there...

**Comment by lukasIO** [comment] 2023-03-02 13:25
closing due to missing feedback

**Closed by lukasIO** 2023-03-02 13:25 UTC
