### ISSUE TITLE
the demo seem to have issues with ios safari

### ISSUE THREAD

**Issue by jason-shen** [livekit/client-sdk-js#92] opened 2021-12-17 09:26 UTC
have notice an issue when using ios safari on ios 15, the page gets reload soon as i give permissions to the cam and mic, has any one else notice that?

**Comment by jason-shen** [comment] 2021-12-17 09:44
>

**Comment by davidzhao** [comment] 2021-12-19 07:32
@jason-shen I think this is the H.264 bug with Safari 15. I've confirmed that
1. this doesn't happen with Safari Tech Preview
2. when restricting server to VP8 (via enabled_codecs), it works as intended.

**Comment by jason-shen** [comment] 2021-12-20 04:16
cool thanks for the reply there @davidzhao will give that a shot

**Comment by davidzhao** [comment] 2021-12-27 23:24
confirmed this is fixed in Safari 15.2

https://bugs.webkit.org/show_bug.cgi?id=232006

**Closed by davidzhao** 2021-12-27 23:24 UTC
