### ISSUE TITLE
Initial connection failed with ConnectionError: could not establish signal connection: RTCPeerConnection is not a constructor

### ISSUE THREAD

**Issue by azr-arch** [livekit/client-sdk-js#969] opened 2023-12-20 09:13 UTC
**Describe the bug**
Trying to use livekit in nextjs 14, but getting this errors several times
```
Initial connection failed with ConnectionError: could not establish signal connection: RTCPeerConnection is not a constructor. Retrying with another region: <my_livekit_cloud_url>
```
then disconnected notification 

**Screenshots**
![livekit error](https://github.com/livekit/livekit/assets/79351619/281a7005-9353-43d9-886c-b6ac31a4bd2d)

"livekit-client": "^1.15.4",
"livekit-server-sdk": "^1.2.7",

**Comment by davidzhao** [comment] 2023-12-20 16:23
@azr-arch this is showing up because you are using the client SDK from a server-side page/component. LiveKit cannot be used from the server side. It requires access to WebRTC APIs that only exists in the browser.

**Comment by lukasIO** [comment] 2023-12-20 17:50
write [`"use client"`](https://nextjs.org/docs/app/building-your-application/rendering/client-components#using-client-components-in-nextjs) on the top of your component to make sure it doesn't run on the server within next.

**Comment by azr-arch** [comment] 2023-12-21 05:14
@davidzhao  @lukasIO 

```
"use client";

import "@livekit/components-styles";
import {
    LiveKitRoom,
    VideoConference,
    GridLayout,
    ParticipantTile,
} from "@livekit/components-react";
import { useEffect, useState } from "react";
import { useChat } from "@context/ChatContext";

export const MediaRoom = ({ callId, currUser }) => {
    const name = currUser.name;
    const [token, setToken] = useState("");

    useEffect(() => {
        if (!callId || !name) return;

        (async () => {
            try {
                const res = await fetch(
                    `/api/get-participant-token?room=${callId}&username=${name}`
                );

                console.log(res);
                const data = await res.json();
                console.log({ data });
                setToken(data.token);
            } catch (error) {
                console.log(error);
            }
        })();
    }, [callId, name]);

    if (token === "") {
        return <p>Loading...</p>;
    }

    return (
        <LiveKitRoom
            video={true}
            audio={true}
            token={token}
            serverUrl={process.env.NEXT_PUBLIC_LIVEKIT_URL}
            data-lk-theme="default"
        >
            <VideoConference />
        </LiveKitRoom>
    );
};
```

and the component in which i am using this is also a client component,
the error only comes in edge browser, its working fine in firefox

**Comment by lukasIO** [comment] 2023-12-21 14:36
It's unclear what's going on, try deleting the `useChat` import at the top as that might do some server side import?

What's the behaviour in Chrome?

**Comment by azr-arch** [comment] 2023-12-22 10:32
> It's unclear what's going on, try deleting the `useChat` import at the top as that might do some server side import?
> 
> What's the behaviour in Chrome?

dont have chrome, and i tried removing the unused imports including useChat, but didnt work

**Comment by lukasIO** [comment] 2023-12-23 08:55
please provide a minimal reproduction example/repository that shows the problem.

**Comment by wxl17839938583** [comment] 2024-02-01 10:33
I have encountered the same problem. My JavaScript demo runs normally in Edge, but reports the same error in FireFox and Chrome. It seems that the desktop version in Readme is supported by all three browsers, and I cannot understand the source code WebRTC reference and don't know why. now the project can only be used in Edge.distressed.The leader asked me to handle this issue

**Comment by lukasIO** [comment] 2024-02-01 16:55
hi @wxl17839938583 , 

we don't have any means to reproduce this error,  please provide a minimal reproduction example/repository that shows the problem.

**Comment by wxl17839938583** [comment] 2024-02-04 05:19
import {ref} from 'vue';
import { Room} from 'livekit-client';
const roomRef = ref(null)

const connectLiveKit = async () => {
  const token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDcyODI4NDYsImlzcyI6IkFQSW10N1padnhpU2ZKQyIsIm5hbWUiOiIxMTEiLCJuYmYiOjE3MDcwMjM2NDYsInN1YiI6IjM5ODZkMmI2OGVjMDhmOTkxMzU2MDVhZWU3MTEyMjhjLVBlb3BsZS1fV2VicGhvbmUiLCJ2aWRlbyI6eyJyb29tIjoiMzk4NmQyYjY4ZWMwOGY5OTEzNTYwNWFlZTcxMTIyOGNfV2VicGhvbmUiLCJyb29tSm9pbiI6dHJ1ZX19.LYSxTCDde8vRbo_yYLfYNzthTLJNiHytD_ut6LYqKGM'
  const wsURL = 'wss://robotics-nakama.lotuscars.com.cn';
  roomRef.value = new Room();
  roomRef.value.prepareConnection(wsURL, token);
  await roomRef.value.connect(wsURL, token);
}
connectLiveKit()

**Comment by wxl17839938583** [comment] 2024-02-04 05:20
import {ref} from 'vue';
import { Room} from 'livekit-client';
const roomRef = ref(null)

const connectLiveKit = async () => {
  const token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDcyODI4NDYsImlzcyI6IkFQSW10N1padnhpU2ZKQyIsIm5hbWUiOiIxMTEiLCJuYmYiOjE3MDcwMjM2NDYsInN1YiI6IjM5ODZkMmI2OGVjMDhmOTkxMzU2MDVhZWU3MTEyMjhjLVBlb3BsZS1fV2VicGhvbmUiLCJ2aWRlbyI6eyJyb29tIjoiMzk4NmQyYjY4ZWMwOGY5OTEzNTYwNWFlZTcxMTIyOGNfV2VicGhvbmUiLCJyb29tSm9pbiI6dHJ1ZX19.LYSxTCDde8vRbo_yYLfYNzthTLJNiHytD_ut6LYqKGM'
  const wsURL = 'wss://xxx.com.cn';
  roomRef.value = new Room();
  roomRef.value.prepareConnection(wsURL, token);
  await roomRef.value.connect(wsURL, token);
}
connectLiveKit()

**Comment by wxl17839938583** [comment] 2024-02-04 05:21
> hi @wxl17839938583 ,
> 
> we don't have any means to reproduce this error, please provide a minimal reproduction example/repository that shows the problem.

import {ref} from 'vue';
import { Room} from 'livekit-client';
const roomRef = ref(null)

const connectLiveKit = async () => {
  const token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDcyODI4NDYsImlzcyI6IkFQSW10N1padnhpU2ZKQyIsIm5hbWUiOiIxMTEiLCJuYmYiOjE3MDcwMjM2NDYsInN1YiI6IjM5ODZkMmI2OGVjMDhmOTkxMzU2MDVhZWU3MTEyMjhjLVBlb3BsZS1fV2VicGhvbmUiLCJ2aWRlbyI6eyJyb29tIjoiMzk4NmQyYjY4ZWMwOGY5OTEzNTYwNWFlZTcxMTIyOGNfV2VicGhvbmUiLCJyb29tSm9pbiI6dHJ1ZX19.LYSxTCDde8vRbo_yYLfYNzthTLJNiHytD_ut6LYqKGM'
  const wsURL = 'wss://robotics-nakama.lotuscars.com.cn';
  roomRef.value = new Room();
  roomRef.value.prepareConnection(wsURL, token);
  await roomRef.value.connect(wsURL, token);
}
connectLiveKit()

**Comment by wxl17839938583** [comment] 2024-02-04 05:29
> hi @wxl17839938583 ,
> 
> we don't have any means to reproduce this error, please provide a minimal reproduction example/repository that shows the problem.

after simplification, this can be reproduced: 

``` 
import {ref} from 'vue';
import { Room} from 'livekit-client';
const roomRef = ref(null)

const connectLiveKit = async () => {
  const token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDcyODI4NDYsImlzcyI6IkFQSW10N1padnhpU2ZKQyIsIm5hbWUiOiIxMTEiLCJuYmYiOjE3MDcwMjM2NDYsInN1YiI6IjM5ODZkMmI2OGVjMDhmOTkxMzU2MDVhZWU3MTEyMjhjLVBlb3BsZS1fV2VicGhvbmUiLCJ2aWRlbyI6eyJyb29tIjoiMzk4NmQyYjY4ZWMwOGY5OTEzNTYwNWFlZTcxMTIyOGNfV2VicGhvbmUiLCJyb29tSm9pbiI6dHJ1ZX19.LYSxTCDde8vRbo_yYLfYNzthTLJNiHytD_ut6LYqKGM'
  const wsURL = 'wss://xxx.com.cn';
  roomRef.value = new Room();
  roomRef.value.prepareConnection(wsURL, token);
  await roomRef.value.connect(wsURL, token);
}
connectLiveKit()
```

**Comment by wxl17839938583** [comment] 2024-02-04 05:32
![image](https://github.com/livekit/client-sdk-js/assets/85285568/4f81a002-19df-4df8-8a46-929dd0a70a32)

**Comment by wxl17839938583** [comment] 2024-02-04 05:34
Error reported by Chrome browser

**Comment by wxl17839938583** [comment] 2024-02-04 05:59
@lukasIO  Error reported by Chrome browser

**Comment by lukasIO** [comment] 2024-02-04 09:29
> after simplification, this can be reproduced:

thanks, but for a reproduction, we'd need a repository that we can run. And also more information about which browser versions you're seeing this on. 
You could create the reproduction e.g. on stackblitz.com, if that's easier than sharing a github repo.

**Comment by wxl17839938583** [comment] 2024-02-05 02:57
@lukasIO  thanks,
May I ask if LiveKit supports Chrome version 80.0.3987.132 (official version) (64 bit)

**Comment by lukasIO** [comment] 2024-02-05 09:42
generally supported browser versions are defined here https://github.com/livekit/client-sdk-js/blob/main/.browserslistrc

**Comment by wxl17839938583** [comment] 2024-02-07 03:28
So it seems to be supportive

**Comment by davidzhao** [comment] 2024-02-07 05:32
this should be fixed in #1022. it'll be resolved in the next release.

**Comment by lukasIO** [comment] 2024-02-08 17:22
WRT to the original issue: `RTCPeerConnection is not a constructor` - this is most likely caused by a browser extension disabling WebRTC altogether (might be a privacy related one)

**Closed** 2024-02-08 20:26 UTC

**Comment by ciaoamigoschat** [comment] 2024-04-04 19:20
<img width="1202" alt="Screenshot 2024-04-04 alle 21 19 32" src="https://github.com/livekit/client-sdk-js/assets/18501887/a10f8a05-e570-4782-8abb-91817363dba8">


I am also experiencing the same error: 
'**could not createOffer with closed peer connection. Initial connection failed with ConnectionError: could not establish pc connection. Retrying with another region...**' 
and immediately after:
 **'Could not createOffer with closed peer connection.**' 
I'm using the latest version of Google Chrome on Mac. Essentially, the connection keeps disconnecting and reconnecting after a few seconds.
